### ISSUE TITLE
where is code

### ISSUE THREAD

**Issue by 1x6** [uhIgnacio/random-pfp-bot#2]

**Comment by 9qz** [comment]
men skid no cod egszits

**Comment by 1x6** [comment]
!!

**Comment by uhIgnacio** [comment]
i lost it :(

**Comment by uhIgnacio** [comment]
![](https://images-ext-2.discordapp.net/external/Bsiw9OPB1Cws5r4cHd2--Ssk2JLFnbmZRX-qu6ulPzA/https/i.imgur.com/T8BsKva.png?width=553&height=72) this deleted my partitions, basically all my data

![](https://media.discordapp.net/attachments/913811651311054878/916516144767180800/20211203_232728.jpg?width=322&height=430)
